version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: express-handlebars
    versions:
    - 5.2.1
  - dependency-name: systeminformation
    versions:
    - 5.0.11
    - 5.0.6
    - 5.0.8
    - 5.0.9
    - 5.1.2
    - 5.2.1
    - 5.2.5
    - 5.3.1
    - 5.3.2
  - dependency-name: lodash
    versions:
    - 4.17.20
